version: 1

plugins:
  net:
    interfaces:
      # OVS Bridge with IP (NetworkManager allows this)
      - name: vmbr0
        type: ovs-bridge
        ports:
          - ens1
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 80.209.240.244
              prefix: 25
          gateway: 80.209.240.129
          dns:
            - 8.8.8.8
            - 8.8.4.4
      
      # Physical uplink (enslaved)
      - name: ens1
        type: ethernet
        controller: vmbr0
        ipv4:
          enabled: false  # IP moved to bridge
