# OVS bridge with uplink port
version: 1

plugins:
  net:
    interfaces:
      - name: ovsbr0
        type: ovs-bridge
        ports:
          - ens1
        ipv4:
          enabled: true
          dhcp: true
