version: 1

plugins:
  net:
    interfaces:
      - name: "ens1"
        type: "ethernet"
        ipv4:
          enabled: true
          dhcp: true
  netcfg:
    dns:
      hostname: "castlebox.ghostbridge.tech"
      search_domains:
        - "nm.internal"
        - "."
