version: 1
plugin: network

network:
  interfaces:
    - name: "ens1"
      type: "ethernet"
      ports: []            # sequence required
      ipv4:
        enabled: true
        dhcp: true
        address: []
        gateway: null
        dns: []
  netcfg:
    dns:
      hostname: "castlebox.ghostbridge.tech"
      search_domains: ["nm.internal", "."]
